apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: csharp
  janus-idp.io/tekton: csharp
  backstage.io/kubernetes-id: csharp
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: csharp
resources:
- deployment.yaml
- route.yaml
- service.yaml
